### PR TITLE
Fix the NCI_c3_to_S3 metadata upload issue

### PR DESCRIPTION
**Pull request by supermarkion**
Hi, @omad 

Based on the Airflow log you found:

``[2021-06-15 07:31:08,412] {ssh_operator.py:148} WARNING - fatal error: can't start new thread                                                                                                                                                                                               
[2021-06-15 07:31:09,768] {ssh_operator.py:148} WARNING - c3_to_s3_rolling - ERROR - Failed to sync of ga_ls7e_ard_3/098/075/2021/05/10 because of an error in the sync command - Failed running S3 sync command                                                                            
[2021-06-15 07:31:11,257] {ssh_operator.py:148} WARNING - c3_to_s3_rolling - INFO - Finished uploading metadata to baseline/ga_ls7e_ard_3/098/075/2021/05/10/ga_ls7e_ard_3-2-0_098075_2021-05-10_final.odc-metadata.yaml                                                                    
[2021-06-15 07:31:15,635] {ssh_operator.py:148} WARNING - c3_to_s3_rolling - INFO - Finished uploading STAC metadata to baseline/ga_ls7e_ard_3/098/075/2021/05/10/ga_ls7e_ard_3-2-0_098075_2021-05-10_final.stac-item.json ``

We can located there is a logical error that: if s3 sync crash, the metadata update also happen. Therefore, I moved the metadata update logic within s3 sync try section.

In my PR, it inclues:

1. exclude metadata files in S3 folder sync step (as S2 pipeline: https://github.com/GeoscienceAustralia/dea-airflow/blob/master/scripts/upload_s2_nbart.py#L110)
2. rename update_metadata to uplodate_metadata. Cause it is the first time to upload metadata files to S3
3. move upload_metadata section to S3 folder sync try section. Make sure both can happen together or not.
4. expose S3 sync response code in log file to imporve the UX

Because we plan to move the SNS step to AWS S3 event notification. Therefore, this DAG task will be changed to make sure the expected tif files and metadata files (with updated information) can upload to S3. So there is no need extra job on SNS section.

Cheers

Sai

### CODE REVIEW

**Comment by supermarkion** [comment]
What is more, based on this statement: https://github.com/GeoscienceAustralia/dea-airflow/blob/master/dags/nci_c3_upload_s3.py#L20. We can set the DAG run as '--force-update' mode to 'ignore target data check' when we manually re-run it. Do we believe change the default run mode as '--force-update' is a safe solution cause daily data is not so horrible?

Or, we can change this check: https://github.com/GeoscienceAustralia/dea-airflow/blob/master/scripts/c3_to_s3_rolling.py#L37 to full check? Right now only check the metadata file. We can check all files (e.g. includes the tif files).

**Comment by supermarkion** [comment]
Of course, we can also add another if-else check in update_metadata() to check the target metadata files are in the S3 already or not. Right now, the current update_metadata() is not 'update' metadata, it uploads another metadata. E.g. we can change this check: https://github.com/GeoscienceAustralia/dea-airflow/blob/master/scripts/c3_to_s3_rolling.py#L37 to full check. Right now only check the metadata file. We can check all files.

**Comment by supermarkion** [comment]
We can also add the metadata files as part of exclude pattern in: https://github.com/GeoscienceAustralia/dea-airflow/blob/feature/fix-nci-metadata-always-upload-bug/scripts/c3_to_s3_rolling.py#L428. Then the update_metadata() will become upload_metadata().

**Comment by omad** [comment]
Hey Sai, thanks for the investigations.

I think my preference is to always upload all the data for a given date.

We're using `aws s3 sync`, and it includes logic for not uploading data unnecessarily anyway.

Go ahead and make whatever simplifications that implies.

**From  `aws s3 sync help`**:
> The following sync command syncs objects under a specified  prefix  and
       bucket  to  files  in a local directory by uploading the local files to
       s3.  A local file will require uploading if the size of the local  file
       is  different than the size of the s3 object, the last modified time of
       the local file is newer than the last modified time of the  s3  object,
       or the local file does not exist under the specified bucket and prefix.

**Review by omad — APPROVED** [review]
Thanks!

**Pull request merged**
