### PR TITLE
convert all webapp subdags to web app operator

### PR DESCRIPTION
**Pull request by pindge**
- create ows update operator
- create explorer update operator
- replace all instances of  ows/explorer subdag with their operator

### CODE REVIEW

**Comment by alexgleith** [comment]
Sorry, I can't review Airflow DAGs, I don't know it well enough.

**Comment by pindge** [comment]
> Sorry, I can't review Airflow DAGs, I don't know it well enough.

That's alright Alex, tagged you for awareness, in case you were interested in replacing ows and explorer subdags. NOT real important, subdags are just as good.

**Review by omad — CHANGES_REQUESTED** [review]
Looks groovy Pin! Thanks! I <3 PRs that result in less code.

The other change I'd suggest is some rename refectoring, it's confusing to see `subdag`, which it's not actually anything to do with SubDAGs any more.

**Comment by pindge** [comment]
> Looks groovy Pin! Thanks! I <3 PRs that result in less code.
> 
> The other change I'd suggest is some rename refactoring, it's confusing to see `subdag`, which it's not actually anything to do with SubDAGs anymore.

I did think about it, but those have to be run within a context of an existing dag, for example, the ows operator inherits the dag and extends from it. I couldn't decide on a name that is correct for this.

**Review by omad — APPROVED** [review]
Looks okay then, I'll merge, make a few refactors and flick it back to you Pin. :)

**Comment by pindge** [comment]
> Looks okay then, I'll merge, make a few refactors and flick it back to you Pin. :)

Yay, thanks

**Pull request merged**
