### PR TITLE
automated_reporting: new weekly currency dag

### PR DESCRIPTION
**Pull request by tmacdam**

### CODE REVIEW

**Comment by tmacdam** [comment]
@tmcadam Hi real Tom, or some other admin. I want to get this running this afternoon and I seem to have lost my admin rights to approve this. Can you review and approve please? Thanks

**Comment by tmacdam** [comment]
@tmcadam Hi real Tom, or some other admin. I want to get this running this afternoon and I seem to have lost my admin rights to approve this. Can you review and approve please? Thanks

**Comment by tmacdam** [comment]
@tmcadam Hi real Tom, or some other admin. I want to get this running this afternoon and I seem to have lost my admin rights to merge this. Damien said it looks okay. Can you review and merge please? Cheers

**Comment by tmcadam** [comment]
DON'T APPROVE THIS. IT WAS JUST A TEST PR!!

**Pull request closed without merging**
